<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'GQS Document' }}</title>
    <style>
        @page { margin: 1.5cm 1.1cm 1.7cm 1.1cm; }
        * { box-sizing: border-box; }
        body { font-family: "Helvetica", Arial, sans-serif; color: #1A1A1F; margin: 0; }
        .sheet { padding: 0; }

        /* Header: logo and title vertically centered together, meta on the right */
        .hd-tbl { width: 100%; border-collapse: collapse; border-bottom: 3px solid #A4123F; }
        .hd-tbl td { vertical-align: middle; padding: 0 0 12px; }
        .hd-logo { height: 34px; width: auto; display: block; }
        .hd-title { font-size: 19px; font-weight: 800; color: #1A1A1F; line-height: 1.1; }
        .hd-sub { font-size: 11px; color: #6A6A72; margin-top: 2px; }
        .hd-meta { text-align: right; font-size: 9.5px; color: #6A6A72; line-height: 1.5; }

        .doc-title { font-size: 15px; font-weight: 700; color: #A4123F; margin: 16px 0 4px; }
        .sec { margin-top: 18px; page-break-inside: avoid; }
        .sec-h { font-size: 11px; font-weight: 800; text-transform: uppercase; letter-spacing: .06em; color: #fff; background: #A4123F; padding: 6px 10px; }
        table.data { width: 100%; border-collapse: collapse; font-size: 11px; }
        table.data th { text-align: left; padding: 6px 9px; background: #1C1C21; color: #fff; font-size: 9.5px; text-transform: uppercase; letter-spacing: .03em; }
        table.data td { padding: 6px 9px; border-bottom: 1px solid #E2E2E6; }
        table.data tr:nth-child(even) td { background: #faf7f8; }
        .pill { display: inline-block; font-size: 10px; font-weight: 700; padding: 2px 8px; border-radius: 20px; }
        .pill-red { background: #FBE3E7; color: #C8102E; } .pill-green { background: #DDF3E9; color: #1E7A52; }
        .pill-gold { background: #FBF3DC; color: #8A6D0B; }
        .stats-tbl { width: 100%; border-collapse: separate; border-spacing: 10px 0; margin: 14px 0; }
        .stat { border: 1px solid #E2E2E6; border-top: 3px solid #A4123F; padding: 10px 12px; }
        .stat .n { font-size: 22px; font-weight: 800; } .stat .l { font-size: 10px; color: #6A6A72; }
        .empty { padding: 12px 10px; color: #6A6A72; font-size: 11px; }

        /* Fixed running footer on every page: Astellas Confidential + page number */
        .page-foot { position: fixed; bottom: -1.15cm; left: 0; right: 0; height: 1cm;
            border-top: 1px solid #E2E2E6; padding-top: 5px; font-size: 8.5px; color: #8A8A92; }
        .page-foot .l { float: left; } .page-foot .r { float: right; }
        .page-foot .c { text-align: center; font-weight: 700; color: #6A6A72; letter-spacing: .04em; }
        .pageno:after { content: counter(page) " of " counter(pages); }
    </style>
</head>
<body>
    {{-- Running footer (repeats on every page via position:fixed) --}}
    <div class="page-foot">
        <span class="l">MATC Gowning Qualification System</span>
        <span class="r">Page <span class="pageno"></span></span>
        <div class="c">ASTELLAS CONFIDENTIAL</div>
    </div>

    <div class="sheet">
        <table class="hd-tbl">
            <tr>
                <td>
                    <table style="border-collapse:collapse;"><tr>
                        <td style="padding:0 12px 0 0;vertical-align:middle;"><img class="hd-logo" src="{{ public_path('images/astellas-logo.png') }}" alt="Astellas"></td>
                        <td style="vertical-align:middle;">
                            <div class="hd-title">Gowning Qualification</div>
                            <div class="hd-sub">{{ $org ?? 'MATC, Astellas' }}@if(!empty($site)) · {{ $site }}@endif</div>
                        </td>
                    </tr></table>
                </td>
                <td class="hd-meta">
                    Generated {{ ($generated ?? now()->setTimezone('America/New_York'))->gmpDt() }}<br>
                    Generated by {{ $generatedBy ?? (auth()->user()?->name ?? 'System') }}
                </td>
            </tr>
        </table>

        @yield('body')
    </div>
</body>
</html>
